* Эскизный и технический проект

** Эскизный проект
Задача эскизного проекта: создать прообраз будущей автоматизированной системы
Определяются основные контуры будущей системы, получаются представления об основных чертах

В результате оформляется, согласовывается и утверждается документация в объеме,
необходимом для описания полной совокупности принятых проектных решений и
достаточном для дальнейшего выполнения работ по созданию системы

При разработке Эск. п.:
  - Ведомость эск. пр.
  - Пояснительная записка
  - Схема организационной работы
  - Структурная схема комплекса техн. ср-в
  - Схема функциональной структуры
  - Схема автоматизации

Разработка эск. пр. не является обязательной.

** Технический проект

Техн пр - пакет документации, описывающий окончательные решения по проектированиюэ
АС

Инфо, представленная в техн пр должна быть достаточна для составления рабочего проекта

Техн. пр должен содержать данные об общесистемных прпоектных решениях, алгоритмах
решения задач, расчет эконом показателей АС

Техн. пр. составляется на основании требований ТЗ по определенным стадиям

Сначала происходит составление общего проекта.ю а на его основании состовляются техн пр.
первой и второй очереди

Работы по разработки документов первой и второй очереди могут вестись независимо друг от
друга

Техн пр состоит из:
  - ведомость
  - схема организационной структуры
  - схема функциональной структуры
  - ведомость покупаемых доп изделий
  - перечень данных и сигналов на входе и выходе
