* Термины и определения

** Термины АС

**Автоматизированная система** - система состоящая из персонала и комплекса
ср-в автоматизации его деятельности, реализующая инфо техн. выполнения
установленных функций

**Алгоритм функционирования АС** - алгоритм, задающий условия и
последовательность действий компонентов АС при выполнении ею функций

**Анализ полноты покрытия** - определенные степени, до которой
работы процесса верификации ПО удовлетворяют поставленной цели

**Верификация** - оценка результатов процесса с целью гарантии корректности
и непротиворечивости в отношении входов и стандартов, сущ. для данного процесса

**Взаимодействие АС** - обмен данными, командами и сигналами между
функционирующими АС

**Документация на АС** - комплект связанных документов, полностью определяющих
техн требования к АС, проектные и организационные решения по созданию и
функционированию АС

**Жизненный цикл АС** - совокупность связанных процессов создания и
последовательного изменения состояния АС от формирования исходных требований
к ней до окончания эксплуатации и утилизации комплекса ср-в автоматизации АС

**Интегрированная автоматизированная система** - совокупность двух или более
связанных АС, функционирование которых зависит отрезультатов друг друга так,
что эту совокупность можно рассматривать как единую АС

**Инфо система** - система, организующая хранение и манипулирование инфо о
предметной области

**Иноо совместимость АвтоСистем** - частная совместимость АС, при которой
в АС используются одни и те же данные, а также возможен инфо обмен между
ними

**Инфо обеспечение Авто Системы** - совокупность форм документов,
классификаторов, нормативной базы и реализованных решений по объемам,
размещению и формам существования инфо, применяемой в АС при ее функционировании

**Инфо ср-во** - комплекс упорядоченной относительно постоянной инфо на носителе
данных, описыващей параметры и характеристики заданной области применения, и
соотв. док-ции, предназначенной для поставки пользователю

**Квалификационное тестирование** - тестирование выполняемое с целью убедить
заказчика, что ПО соотв.  заданным требованиям

**Методическое обеспечение Авто Системы** - совокупность док-в, описывающих
техн. функционирования АС, методы выбора и применения пользователями техн
приемов для получения конкретных результатов при функционировании АС

**Организационное обеспечение АС** - совокуп. док-в, устонавливающих
организационную структуру, права и обязанности пользователей и эксплуатационного
персонала АС в условиях функционирования, проверки и обеспечения работоспособности АС

**Пользователь АС** - лицо, участвующее в функционировании АС или использующее
результаты ее работы

**Приемочная док-ция на АС** - док-ция, подтверждающая готовность АС к приемке ее в
использование, соответв. АС требованиям нормативных док-в

**Программная совместимость АС** - частная совместимость АС, характерезуемая
возможностью работы ПО одной системы в другой и обмена ПО, необходимыми для
взаимодействия АС

**Программное изделие в АС** - п ср-во, изготовленное, прошедшее испытания и
поставляемое как продукция производственного назначения для применения в АС

**ПО АС** - совокуп программ на носителях данных и программных док-в,
предназначенная для отладки функционирования и проверки работоспособности АС

**Процесс создания АС** - совокуп работ от формирований требований к исходной
системе до ввода в действие

**Рабочая док-ция на АС** - комплект проектных док-в, содержащий: связанные
решения по системе, по видам обеспечения АС, достаточные для комплектации,
монтажа, наладкии и функционирования АС, ее проверки и обеспечения работоспособности

**Совместимость АС** - комплексное св-во 2-ч или более АС, характеризуемое их
способностью к взаимодействию

**Сообщения АС** - сведенья в виде законченного блока данных, передаваемые
при функционировании АС

**Сопровождение АС** - услуги, необходимые для обеспечения устойчивого
функционирования или разваития

**Спецификация программы** - требования, предъявляемые к программе, которые
должны быть удовлетворены при ее разработке, а также описание задачи, условия и
эффекта действия без указания способа его достижения

**Стадия создания АС** - часть создания АС, установленная нормативными док-ми и
заканчивающаяся выпуском док-ции на АС, содержащей описание полной, в рамках заданных
требований, модели АС назаданном для стадии уровне, или изготовлением несерийных
компонентов АС, или приемкой АС в промшленное использование

**Техн совметсимость** - частная совместимость АС, характеризуемая возможностью
взаимодействия техн ср-в этих систем

**Техн проект АС** - проект проектных док-в АС, разрабатываемый на стадии
"Техн проект", утвержленный в установленном порядке, содержащий основные проектные
решения по системе, ее функциям и всем видам обеспечения АС и достаточный для
разработки рабочей док-ции на АС

**Техн задание на АС** - док, оформленный в установленном порядке и определяющий
цели для создания АС, требования к АС и основные исходные данные, необходимые для
ее разработки, а иакже план-шрафик создания АС

**Техн обеспечение АС** - совокуп всех техн ср-в, используемых при функционировании АС

**Управление конфигурацией** - процесс идентификации и обеспечения целостности
элементов конф системы

**Эксплуат. док-ция на АС** - часть рабочей док-ции на АС, предназначенная для
использования при эксплуат. АС, опрежеляющая правила действия персонала и пользователей
системы при ее функционировании, проверке и обеспечении ее работоспособности

**Этап создания АС** - часть стадии создания АС, выделенная по соображениям единства
характера работ или завершающего результата или специализации исполнителей

**Эффективность АС** - св-во АС, характеризуемое степенью достижения целей, поставленных
при ее создании

** Техн док-ция ИС, назначение техн док-ции

**Техн док-ция** - состовляющая проекта по созданию, внедрению, сопровождению ИС

**Нормативно-методическое обеспечение** - комплекс док-в, регламентирующий
деятельность разработчиков

В комплекс входят:
 - стандарты
 - руководящие док-ты
 - методики и положения
 - инструкции

НМО регламентирует порядок разработки, общие требования к составу и качеству
ПО, связям между компонентами, определяет содержание проектной и программной док-ции

Основным назначение **техн док-ции** является обеспечение эффективных процедур
разработки и использования ИС как ПП, а также организация обмена между разработчиками
и пользователями ИС

*** Функции техн док-ции:
 - Описание возможностей системы
 - обеспечение фиксации принятых и реализованных проектных решений
 - Определение условий функционирования ИС
 - Предоставление инфо об эксплуацтации и обслуживании ИС
 - регламентирование процедуры защиты инфо, регулирование прав различных групп пользователей
 - Определение возможности модернизации системы

*** Вопросы на которые нужно ответить перед составлением Техн док-ции:

 - что и зачем должно быть документировано
 - для кого предназначен тот или иной документ
 - какие ошибки может допустить пользователь и что нудно сделать для их устранения
 - как и в каких условиях будет использоваться документ
 - каковы сроки разработки документов
 - как будет обновляться и поддерживаться док-ция, механизмы и сроки внесения
   изменений и пересмотра док-в, кто ответсвенен за реализацию этих действий,
   а также за хранение, неизменность и контроль за испольнением
 - кто булет оценивать документ и как он соотносится с отраслевыми или ведомственными
   требованиями на сертификацию разработки

*** Требованияи к техн док-ции
 - документы должны быть точными, полными, краткими, иметь четкое и однозначное толкование
 - док-ция должна создаваться параллельно с разработкой самой ИС
 - обязанности по док-нию системы лежат на ее разработчике
 - для повышения эффективности работы с документами должнв использоваться стандарты
